"all":
  "children":
    "bastion":
      "hosts":
        "bastion01":
          "ansible_host": "13.124.215.149"
          "ansible_ssh_private_key_file": "~/.ssh/bastion-key.pem"
    "db":
      "hosts":
        "db01":
          "ansible_host": "10.0.30.186"
          "ansible_ssh_common_args": |
            -o ProxyCommand="ssh -i ~/.ssh/bastion-key.pem -W %h:%p -q adreamin@13.124.215.149"
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
    "was":
      "hosts":
        "was01":
          "ansible_host": "10.0.10.22"
          "ansible_ssh_common_args": |
            -o ProxyCommand="ssh -i ~/.ssh/bastion-key.pem -W %h:%p -q adreamin@13.124.215.149"
            -o StrictHostKeyChecking=no
            -o UserKnownHostsFile=/dev/null
  "vars":
    "ansible_host_key_checking": false
    "ansible_ssh_private_key_file": "~/.ssh/ansible-key.pem"
    "ansible_user": "adreamin"
